### ISSUE TITLE
[Feature request] add support for AptioMemoryFix.efi and AptioInputFix.efi

### ISSUE THREAD

**Issue by hereisderek** [Micky1979/Build_Clover#9] opened 2018-01-20 03:49 UTC
those two drivers are both from [vit9696](https://github.com/vit9696/AptioFixPkg) and are both included in the official clover installer and missing from the script compiled installer

**Comment by Micky1979** [comment] 2018-01-20 13:46
Done, is online. Update the script and call:

`x)update Clover + force edk2 update (no building)
`
...step needed to rebuild BaseTools

**Comment by Micky1979** [comment] 2018-01-20 13:49
Forgot to mention that atm is only possible using Xcode and clang. Using GNU gcc isn't possible without changes..maybe someone should open an issue at vit9696's repository or at Clover team (not sure, maybe a build system problem in tools_def.txt).

**Comment by Micky1979** [comment] 2018-01-20 13:50
I'm closing this issue, but feel free to post again if something goes wrong.

**Comment by Dids** [comment] 2018-01-29 07:51
@Micky1979 Any idea why the `AptioMemoryFix.efi` and `AptioInputFix.efi` drivers are only included in the installer package on the _second_ build, but not on the first?

This is easily reproducible by simply deleting the `~/src` directory, then building (I'm building in headless/non-interactive mode).

It does look like it's building the the drivers just fine, but it's just not including the drivers in the package (on the first run), so I'm guessing it's an ordering issue in the script?

**Comment by Micky1979** [comment] 2018-01-29 20:22
By design (good or bad) You need BaseTools to be already compiled and ensure is a fresh compilation as I stated in my first answer of this issue. Basically Aptio stuff are only downloaded/updated when you force update edk2 that automatically clean it and so to ensure your drivers will be ok and not built by old stuff and yes, this is required once with an old source. Anyway when you download everything for the first time, all the stuff should be already in place and ready. What can make a fail is only (I think) when BaseTools is not yet compiled (see line 825): in this case you should see errors.
Can I ask to post a complete log here, after redownloading all from scratch? I'm sorry but Vodafone (my provider) grant me something like 22KB/sec these days (some announced work in progress on the network) otherwise will took me days. Thanks in advance

**Comment by Micky1979** [comment] 2018-01-30 21:04
@Dids I've just make a fresh checkout of Clover (the entire src directory) and everything(s) is ok since the first time and both AptioMemoryFix.efi and AptioInputFix.efi are in the package.
Can I have please a complete terminal output from you? Thanks!

**Comment by Dids** [comment] 2018-01-31 07:32
@Micky1979 The first build is definitely showing errors, you're right. Here's a few snippets from the first log, as well as full log files for the first and second runs.

```
/bin/sh: /usr/local/bin/mtoc.NEW: No such file or directory
make: *** [/Users/dids/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Platform/AptioInputFix/AptioInputFix/DEBUG/AptioInputFix.efi] Error 127

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/dids/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Platform/AptioInputFix/AptioInputFix]

build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/dids/src/edk2/Build/AptioFixPkg/RELEASE_XCODE8/X64/AptioFixPkg/Platform/AptioMemoryFix/AptioMemoryFix]

build.py...
 : error F002: Failed to build module
	/Users/dids/src/edk2/AptioFixPkg/Platform/AptioInputFix/AptioInputFix.inf [X64, XCODE8, RELEASE]
```

I'm guessing the missing `/usr/local/bin/mtoc.NEW` file is related?

---

Full log of the first run (missing AptioMemoryFix and AptioInputFix):
https://www.dropbox.com/s/yddtdfnmszgrrhk/Build_Clover_1.log?dl=0

Full log of the second run (includes AptioMemoryFix and AptioInputFix):
https://www.dropbox.com/s/9ctpk3xycpp70w5/Build_Clover_2.log?dl=0

**Comment by philippetev** [comment] 2018-01-31 16:23
I think I know what's happening. The **AptioFixPkg** module doesn't use the **ebuild.sh** script (bundled with Clover) for building. That script however has a check if **mtoc.NEW** exist at the right place and restores the binary and/or the symlink to it, if needed. Well, without using it, that won't happen on the first run for obvious reasons:
- both the binary and the symlink are missing on totally fresh download of the **src** folder content.
- the binary is missing and the symlink is there, but its broke on **src/edk2** folder, manually deleted by the user.

and building the **AptioFixPkg** module the first time becomes a no-go.

**Comment by Micky1979** [comment] 2018-01-31 17:04
Thanks Guys. Philip already told me that last night about mtoc. 
Philipe, what about cloning/adjust code from ebuild.sh to install mtoc.NEW?

`

checkXcode () {
    XCODE_BUILD="/usr/bin/xcodebuild"
    local LOCALBIN="/usr/local/bin"
    local CLOVERBIN="${CLOVERROOT}/BuildTools/usr/local/bin"
    if [[ ! -x "${XCODE_BUILD}" ]]; then
        echo "ERROR: Install Xcode Tools from Apple before using this script." >&2
        exit 1
    elif [[ -f "${CLOVERBIN}/mtoc.NEW.zip" ]]; then
        unzip -qo "${CLOVERBIN}/mtoc.NEW.zip" -d "${CLOVERBIN}"
        [[ ! -d "${LOCALBIN}" ]] && sudo mkdir -p "${LOCALBIN}"
        if [[ ! -x "${LOCALBIN}/mtoc" ]]; then
            echo "Installing mtoc"
            sudo ln -s "${CLOVERBIN}/mtoc.NEW" "${LOCALBIN}/mtoc"
        fi
        if [[ ! -x "${LOCALBIN}/mtoc.NEW" ]]; then
            echo "Installing mtoc.NEW"
            sudo ln -s "${CLOVERBIN}/mtoc.NEW" "${LOCALBIN}/mtoc.NEW"
        fi
        sudo -k
    fi
}`

let me know

**Comment by philippetev** [comment] 2018-01-31 17:15
I think I've fixed that already. Guys, please check the work branch. The solution I've chosen doesn't even require sudo.

**Comment by Micky1979** [comment] 2018-01-31 17:21
looks good to me. @Dids can you kindly try it?

**Comment by Micky1979** [comment] 2018-01-31 17:30
Ops, Philip, can you unzip it elsewhere?
EDIT
ok ebuild.sh doing just the same! forget me.

**Comment by philippetev** [comment] 2018-01-31 17:35
It's the same place where ebuild.sh will unzip it and doing it twice (once by this script and second time by ebuild.sh) won't be a problem. After all, the new **mtocCheck** function won't even be executed on the next script run, assuming the mtoc binary and symlink are in place.

**Comment by Dids** [comment] 2018-01-31 18:30
I can confirm that the work branch version works great!

**Comment by Micky1979** [comment] 2018-01-31 18:33
Good! I'm closing the issue. Philip, please commit your changes to the master ;-)

@Dids, thanks for reporting.

**Closed as completed by Micky1979** 2018-01-31 18:33 UTC

**Comment by Dids** [comment] 2018-02-27 18:53
@Micky1979 @philippetev I believe the issue is still there with non-interactive builds.

Here's the error from a fresh, non-interactive build (Build_Clover v4.7.5):

```
/bin/sh: /Users/vagrant/src/opt/local/bin/mtoc.NEW: No such file or directory
make: *** [/Users/vagrant/src/edk2/Build/Clover/RELEASE_XCODE8/X64/Clover/CloverEFI/OsxDxeIpl/DxeIpl/DEBUG/DxeIpl.efi] Error 127
build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/Clover/RELEASE_XCODE8/X64/Clover/CloverEFI/OsxDxeIpl/DxeIpl]
build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/Clover/RELEASE_XCODE8/X64/MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer]
build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/Clover/RELEASE_XCODE8/X64/MdeModulePkg/Universal/PCD/Dxe/Pcd]
build.py...
 : error 7000: Failed to execute command
	make tbuild [/Users/vagrant/src/edk2/Build/Clover/RELEASE_XCODE8/X64/Clover/CloverEFI/OsxDxeCore/DxeMain]
build.py...
 : error F002: Failed to build module
	/Users/vagrant/src/edk2/Clover/CloverEFI/OsxDxeIpl/DxeIpl.inf [X64, XCODE8, RELEASE]
- Failed -
Build end time: 10:51:19, Feb.27 2018
Build total time: 00:00:36
o_Ops, ./ebuild.sh exited with error(s), aborting..
```

Note that building it _again_ after the initial failed build works, but fresh (eg. with `~/src` removed) won't.

**Comment by philippetev** [comment] 2018-02-28 07:53
Tried your scenario with both interactive and non-interactive mode and wasn't able to reproduce your problem. mtoc was found by the script in both modes. Could you try to execute the script like this:
`bash -x buildclover`
and post the output?

**Comment by Dids** [comment] 2018-02-28 09:04
Here's the build log (it's pretty hefty):
https://www.dropbox.com/s/hsaglq80w2os47j/Build_Clover.log?dl=0

Just for reference, and because it might very well be related, here's my `BuildCloverConfig.txt` for headless/non-interactive running:

```sh
XCODE=
GNU=
Build_Tool=XCODE
SUGGESTED_CLOVER_REV=
MODE=S
DEFAULT_MACROS=-D NO_GRUB_DRIVERS_EMBEDDED
PATCHES=
BUILD_PKG=YES
BUILD_ISO=NO
USEHFSPLUS=YES
USEAPFS=YES
USENTFS=YES
GITHUB=https://raw.githubusercontent.com/Micky1979/Build_Clover/master/Build_Clover.command
CLOVER_REP=svn://svn.code.sf.net/p/cloverefiboot/code
EDK2_REP=svn://svn.code.sf.net/p/edk2/code/trunk/edk2
DISABLE_CLEAR=YES
MY_SCRIPT=
FAST_UPDATE=NO
INTERACTIVE=NO
ForceEDK2Update=1
ARCH=X64
FORCEREBUILD=-fr
SHOWCCP_ADVERTISE=NO
SVN_UPDATE_ACCEPT_ARG=tf
```

**Comment by philippetev** [comment] 2018-02-28 10:16
Ok, now I think I know where the problem is. Just pushed a new version in the work branch, please, test it with the same scenario and tell me if it works.

**Comment by Dids** [comment] 2018-02-28 10:53
@philippetev That worked like a charm!

**Comment by philippetev** [comment] 2018-02-28 11:15
You know, I'm going to push another update. Made some improvements to that code, so it should be called only once. May I ask you to test it, when it's done?

**Comment by Dids** [comment] 2018-02-28 11:16
Sure, just let me know when.

**Comment by philippetev** [comment] 2018-02-28 11:36
Ok, it's pushed.

**Comment by Dids** [comment] 2018-02-28 12:01
Yeah, still works great. :)
